version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      projectwallace:
        patterns:
          - '@projectwallace/*'
      npm-all:
        patterns:
          - '*'
        exclude-patterns:
          - '@projectwallace/*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'
